version: '3.8'

x-networks: &networks
    networks:
        - default

x-postgres: &postgres
    <<: *networks
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
        POSTGRES_DB: ${POSTGRES_DB:-app}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
        POSTGRES_USER: ${POSTGRES_USER:-app}

services:
    php:
        <<: *networks
        container_name: php
        hostname: php
        user: app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "${PHP_HOST_PORT:-8337}:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

    postgres:
        <<: *postgres
        container_name: postgres
        hostname: postgres
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        networks:
            - default
        ports:
            - "${POSTGRES_HOST_PORT:-54321}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw

    postgres_test:
        <<: *postgres
        container_name: postgres_test
        hostname:  postgres_test
        ports:
            - "${POSTGRES_TEST_HOST_PORT:-54322}:5432"

volumes:
  postgres_data:

networks:
    default: ~
